package: 
  name: pywitness
  version: 1.4.2

source: 
  path: ../

build: 
  preserve_egg_dir: True

requirements: 

  build:
    - python
    - setuptools
    - pip
    - cython
    - pybind11
    - pytz=2021.3
    - xlrd
    - openpyxl
    - scipy
    - matplotlib
    - ipython
#    - pyreadstat

  run:
    - pytz=2021.3
    - xlrd
    - openpyxl
    - pandas
    - scipy
    - matplotlib
    - ipython
#    - pyreadstat

test:
  imports:

about:
  home: