package: 
  name: pywitness
  version: 1.4

source: 
  git_url: https://github.com/lmickes/pyWitness
  git_rev: v1.4

build: 
  preserve_egg_dir: True

requirements: 

  build:
    - python
    - setuptools
    - pip
    - cython
    - pybind11
    - pytz=2021.3
    - xlrd
    - openpyxl
    - scipy
    - matplotlib
    - ipython
    - pyreadstat

  run:
    - pytz=2021.3
    - xlrd
    - openpyxl
    - pandas
    - scipy
    - matplotlib
    - ipython
    - pyreadstat

test:
  imports:

about:
  home: