name: Conda upload

on:
  workflow_dispatch:
  release:
    types:
      - published


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: publish-to-conda
        uses: crabisoft/publish-conda@v1.0.0
        with:
          sub-directory: 'conda'
          build-channels: 'conda-forge'
          upload-channel: 'lmickes'
          platforms: 'win-64 osx-64'
          stable: true
          token: ${{ secrets.ANACONDA_TOKEN }}

